import Head from 'next/head'
import Image from 'next/image'

import {cLink, boxWidth, boxHeight } from '../styles/variables.module.scss'
import {makeABox} from "../functions/make-a-box";

export default function Home() {
  return (
    <>
      
      {/*{makeABox()}*/}
      
      <div className="container">
        <Head>
          <title>Welcome to Next.js</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className="main">
          
          <h1 className="title">
            Welcome to <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">Next.js!</a>
          </h1>
          
          <div className="description">
            {/*<p>The link color is {cLink}</p>*/}
            {/*<p>The link color is <span style={{color: cLink}}>{cLink}</span></p>*/}
            {/*<p>Please visit <a href="rainieratlantic">Rainier Atlantic</a></p>*/}
          </div>
          
          {/* Boxes container */}
          <div className="boxes">
            <div className="box box-dimensions">
              I am a box
              {/*<br/> {boxWidth} x {boxHeight}*/}
            </div>
          </div>
          
        </main>
      </div>
      
    </>
  )
}
