import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { cLink } from '../styles/variables.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          The special color is <span style={{color: cLink}}>{ cLink }</span>
        </p>
      </main>
    </div>
  )
}
